fix: podcast episode preview content
freeCodeCamp/mobile pull request #1177
Opened 2024-01-19 08:57 UTC by Sanket6652

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Removed HTML widget because of maxLines property did not work as expected if the content contains elements like line breaks or other block-level elements that can break the line. That's why I added the text widget, by parsing the body of the description used as textcontent in the widget. By using the text widget we can see max lines 3

Closes #1175

2024-01-19 12:10 UTC, Sembauke submitted a review, later dismissed

2024-01-19 12:17 UTC, Sembauke commented
Links won't be clickable anymore, we should probably use the HTML widget, despite the text being longer than 3 lines.

2024-01-20 04:31 UTC, Sanket6652 commented
ok, the link is only clickable if it has <href> tag only, some of the links are not in href tag.

2024-01-20 12:59 UTC, Nirajn2311 commented on mobile-app/lib/ui/widgets/podcast_widgets/podcast_tilte_widget.dart
> +      // ),
These lines do need to be removed.

2024-01-20 13:02 UTC, Nirajn2311 requested changes
The analyzer has reported some errors in your code. You can view them by running `flutter analyze`. Also where are you making these changes from as they seem to be somehow bypassing the pre-commit check.

2024-01-23 15:25 UTC, Nirajn2311 approved these changes

2024-01-23 15:26 UTC, merged