feat: authentication
freeCodeCamp/mobile pull request #310
Opened 2022-04-16 19:51 UTC by Nirajn2311

2022-05-12 16:12 UTC, Sembauke requested changes

2022-05-12 16:12 UTC, Sembauke commented on mobile-app/lib/service/authentication_service.dart
> +        log('_jwtAccessToken: $_jwtAccessToken');
```suggestion
        showKeys(); 
```

2022-05-12 16:13 UTC, Nirajn2311 commented on mobile-app/lib/ui/widgets/drawer_widget/drawer_widget_view.dart
> +                    model.showForum
I made it a separate page as then we could add extra buttons which would help in debugging when we come across any issue.

2022-05-13 07:04 UTC, Nirajn2311 commented on mobile-app/lib/service/authentication_service.dart
> +        log('_jwtAccessToken: $_jwtAccessToken');
Ahh yes good catch

2022-05-13 07:30 UTC, Sembauke commented
The test failed but it doesn't really matter.

2022-05-13 07:30 UTC, Sembauke approved these changes

2022-05-13 07:30 UTC, merged