Preview feature made unavailable for JS challenges
freeCodeCamp/mobile pull request #915
Opened 2023-04-14 17:57 UTC by Spyy004

Checklist:

- [x ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x ] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #567

As far as I understood, every challenge has a type. I could only find challenges of two types. 0 and 1. So challenge with 0 were of HTML, CSS and challenge of type 1 were js, DSA, euler project.

If my understanding is correct, then the preview function won't work for any challenge type that doesn't deal with UI and hence I coded according to that thought process. 

Also, I have changed the <meta> thing because it was giving a warning when I was trying to push the code.

Please review the PR and provide valuable feedback. If you find the implementation to be correct, Please merge the PR. If I am thinking in the wrong direction, please tell me the exact requirement so that I can fix it

2023-04-15 17:07 UTC, Spyy004 commented
closed it by mistake

2023-04-19 06:55 UTC, Sembauke requested changes
Hey @Spyy004,

Thank you for making this change, it looks good!

In the near future we will be implementing a console, that will show console.log messages. Instead of adding a new snackbar function. It would be nice to instead point it to the already available function which states that the console is not yet available.

2023-04-19 07:00 UTC, Sembauke commented
Also, for future reference, you should never directly commit changes on your main branch. You should check out on a feature branch instead. 

No harm done of course.

2023-04-19 07:18 UTC, Spyy004 commented
> Hey @Spyy004,
> 
> Thank you for making this change, it looks good!
> 
> In the near future we will be implementing a console, that will show console.log messages. Instead of adding a new snackbar function. It would be nice to instead point it to the already available function which states that the console is not yet available.

Hmm got it. Will work on it and push the code. Thanks for the feedback

2023-04-19 07:19 UTC, Spyy004 commented
> Also, for future reference, you should never directly commit changes on your main branch. You should check out on a feature branch instead.
> 
> No harm done of course.

Oh yeah sorry for that. Don't know how i missed this! :(

2023-04-20 08:39 UTC, closed without merging